package com.zil.seraphim.demo.mapper;

import com.zil.seraphim.demo.model.Character;
import com.zil.seraphim.demo.model.CharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int countByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int deleteByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int insert(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int insertSelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    List<Character> selectByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    Character selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int updateByExample(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int updateByPrimaryKeySelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Aug 08 14:07:07 CST 2015
     */
    int updateByPrimaryKey(Character record);
}