package com.zil.samwise.demo.model;

public class Character {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.id
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.characterId
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    private String characterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.characterName
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    private String characterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.characterLevel
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    private String characterLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.id
     *
     * @return the value of character.id
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.id
     *
     * @param id the value for character.id
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.characterId
     *
     * @return the value of character.characterId
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public String getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.characterId
     *
     * @param characterId the value for character.characterId
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public void setCharacterId(String characterId) {
        this.characterId = characterId == null ? null : characterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.characterName
     *
     * @return the value of character.characterName
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public String getCharacterName() {
        return characterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.characterName
     *
     * @param characterName the value for character.characterName
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public void setCharacterName(String characterName) {
        this.characterName = characterName == null ? null : characterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.characterLevel
     *
     * @return the value of character.characterLevel
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public String getCharacterLevel() {
        return characterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.characterLevel
     *
     * @param characterLevel the value for character.characterLevel
     *
     * @mbggenerated Sun Jul 26 01:33:44 CST 2015
     */
    public void setCharacterLevel(String characterLevel) {
        this.characterLevel = characterLevel == null ? null : characterLevel.trim();
    }
}