package com.zil.seraphim.demo.model;

import java.util.ArrayList;
import java.util.List;

public class CharacterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public CharacterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIsNull() {
            addCriterion("characterId is null");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIsNotNull() {
            addCriterion("characterId is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterIdEqualTo(String value) {
            addCriterion("characterId =", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotEqualTo(String value) {
            addCriterion("characterId <>", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdGreaterThan(String value) {
            addCriterion("characterId >", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdGreaterThanOrEqualTo(String value) {
            addCriterion("characterId >=", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdLessThan(String value) {
            addCriterion("characterId <", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdLessThanOrEqualTo(String value) {
            addCriterion("characterId <=", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdLike(String value) {
            addCriterion("characterId like", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotLike(String value) {
            addCriterion("characterId not like", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIn(List<String> values) {
            addCriterion("characterId in", values, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotIn(List<String> values) {
            addCriterion("characterId not in", values, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdBetween(String value1, String value2) {
            addCriterion("characterId between", value1, value2, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotBetween(String value1, String value2) {
            addCriterion("characterId not between", value1, value2, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIsNull() {
            addCriterion("characterName is null");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIsNotNull() {
            addCriterion("characterName is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterNameEqualTo(String value) {
            addCriterion("characterName =", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotEqualTo(String value) {
            addCriterion("characterName <>", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameGreaterThan(String value) {
            addCriterion("characterName >", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameGreaterThanOrEqualTo(String value) {
            addCriterion("characterName >=", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLessThan(String value) {
            addCriterion("characterName <", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLessThanOrEqualTo(String value) {
            addCriterion("characterName <=", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLike(String value) {
            addCriterion("characterName like", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotLike(String value) {
            addCriterion("characterName not like", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIn(List<String> values) {
            addCriterion("characterName in", values, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotIn(List<String> values) {
            addCriterion("characterName not in", values, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameBetween(String value1, String value2) {
            addCriterion("characterName between", value1, value2, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotBetween(String value1, String value2) {
            addCriterion("characterName not between", value1, value2, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelIsNull() {
            addCriterion("characterLevel is null");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelIsNotNull() {
            addCriterion("characterLevel is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelEqualTo(String value) {
            addCriterion("characterLevel =", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelNotEqualTo(String value) {
            addCriterion("characterLevel <>", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelGreaterThan(String value) {
            addCriterion("characterLevel >", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelGreaterThanOrEqualTo(String value) {
            addCriterion("characterLevel >=", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelLessThan(String value) {
            addCriterion("characterLevel <", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelLessThanOrEqualTo(String value) {
            addCriterion("characterLevel <=", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelLike(String value) {
            addCriterion("characterLevel like", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelNotLike(String value) {
            addCriterion("characterLevel not like", value, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelIn(List<String> values) {
            addCriterion("characterLevel in", values, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelNotIn(List<String> values) {
            addCriterion("characterLevel not in", values, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelBetween(String value1, String value2) {
            addCriterion("characterLevel between", value1, value2, "characterLevel");
            return (Criteria) this;
        }

        public Criteria andCharacterLevelNotBetween(String value1, String value2) {
            addCriterion("characterLevel not between", value1, value2, "characterLevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 02 16:12:07 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated Sun Aug 02 16:12:07 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}